import { MigrationInterface, QueryRunner } from "typeorm";

export class Partner1744959279111 implements MigrationInterface {
    name = 'Partner1744959279111'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`login_log\` (\`id\` int NOT NULL AUTO_INCREMENT, \`ip\` varchar(255) NULL COMMENT '登录 IP（可拓展）', \`device\` varchar(255) NULL COMMENT '设备信息（可拓展）', \`loginDate\` date NOT NULL COMMENT '登录日期（冗余字段，方便直接按日期查）', \`userId\` int NOT NULL COMMENT '用户id', \`createtime\` datetime(6) NOT NULL COMMENT '第一次登录时间' DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`reward\` (\`id\` int NOT NULL AUTO_INCREMENT COMMENT 'id', \`title\` varchar(255) NOT NULL COMMENT '标题', \`reward\` int NOT NULL COMMENT '奖励', \`description\` varchar(255) NULL COMMENT '描述', \`image\` varchar(255) NULL COMMENT '图片', \`category\` enum ('date', 'food', 'service', 'gift', 'other') NOT NULL COMMENT '分类', \`startDate\` varchar(255) NULL COMMENT '开始日期', \`endDate\` varchar(255) NULL COMMENT '结束日期', \`validity\` enum ('permanent', 'limited') NOT NULL COMMENT '时长', \`totalNum\` int NOT NULL COMMENT '总数量', \`enableNum\` int NOT NULL COMMENT '可使用', \`isHot\` int NOT NULL COMMENT '是否热门 0非热门，1热门' DEFAULT '0', \`status\` enum ('pending', 'in-progress', 'completed') NOT NULL COMMENT '状态' DEFAULT 'pending', \`createtime\` datetime(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`updatetime\` datetime(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`createby\` int NOT NULL COMMENT '创建人id', \`createName\` varchar(255) NOT NULL COMMENT '创建人名称', \`updateby\` int NULL COMMENT '更新人id', \`updateName\` varchar(255) NULL COMMENT '更新人名称', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`task\` (\`id\` int NOT NULL AUTO_INCREMENT COMMENT '任务id', \`title\` varchar(255) NOT NULL COMMENT '标题', \`description\` varchar(255) NOT NULL COMMENT '描述', \`date\` varchar(255) NOT NULL COMMENT '日期', \`time\` varchar(255) NOT NULL COMMENT '时间', \`priority\` enum ('high', 'medium', 'low') NOT NULL COMMENT '优先级', \`reward\` int NOT NULL COMMENT '奖励', \`status\` enum ('pending', 'in-progress', 'completed') NOT NULL COMMENT '状态', \`location\` varchar(255) NULL COMMENT '位置', \`createtime\` datetime(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`updatetime\` datetime(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`createby\` int NOT NULL COMMENT '创建人id', \`createName\` varchar(255) NOT NULL COMMENT '创建人名称', \`updateby\` int NULL COMMENT '更新人id', \`updateName\` varchar(255) NULL COMMENT '更新人名称', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sub_task\` (\`id\` int NOT NULL AUTO_INCREMENT COMMENT '子任务id', \`title\` varchar(255) NOT NULL COMMENT '标题', \`description\` varchar(255) NULL COMMENT '描述', \`taskId\` int NOT NULL COMMENT '任务id', \`status\` enum ('pending', 'completed') NOT NULL COMMENT '状态', \`createtime\` datetime(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`updatetime\` datetime(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`createby\` int NOT NULL COMMENT '创建人id', \`createName\` varchar(255) NOT NULL COMMENT '创建人名称', \`updateby\` int NULL COMMENT '更新人id', \`updateName\` varchar(255) NULL COMMENT '更新人名称', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user\` (\`id\` int NOT NULL AUTO_INCREMENT COMMENT '用户id', \`uId\` varchar(255) NULL COMMENT '唯一id', \`partnerId\` int NULL COMMENT '伙伴id', \`bindingTime\` datetime NULL COMMENT '绑定日期', \`reward\` int NULL COMMENT '积分' DEFAULT '0', \`avatar\` text NULL COMMENT '头像', \`username\` varchar(255) NOT NULL COMMENT '用户名', \`password\` varchar(255) NOT NULL COMMENT '密码', \`nickname\` varchar(255) NULL COMMENT '昵称', \`sex\` int NOT NULL COMMENT '性别,男性为1,女性为2,未知为3' DEFAULT '1', \`phone\` varchar(45) NULL COMMENT '手机号', \`email\` varchar(45) NULL COMMENT '邮箱', \`userType\` int NOT NULL COMMENT '用户类型：0超级管理员,1管理员,2普通用户' DEFAULT '2', \`status\` tinyint NOT NULL COMMENT '用户状态' DEFAULT 1, \`description\` varchar(255) NULL COMMENT '用户描述', \`createtime\` datetime(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`updatetime\` datetime(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_9208163a1d62dbd34ae753fc6f\` (\`uId\`), UNIQUE INDEX \`IDX_78a916df40e02a9deb1c4b75ed\` (\`username\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`message\` (\`id\` varchar(36) NOT NULL, \`type\` enum ('task', 'user', 'reward', 'system') NOT NULL, \`title\` varchar(255) NOT NULL, \`content\` text NOT NULL, \`isRead\` tinyint NOT NULL DEFAULT 0, \`userId\` int NULL, \`condition\` json NULL, \`createtime\` datetime(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`updatetime\` datetime(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`rule\` (\`id\` int NOT NULL AUTO_INCREMENT COMMENT 'id', \`title\` varchar(255) NOT NULL COMMENT '标题', \`rewardId\` int NOT NULL COMMENT '奖励id', \`createtime\` datetime(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`updatetime\` datetime(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`createby\` int NOT NULL COMMENT '创建人id', \`createName\` varchar(255) NOT NULL COMMENT '创建人名称', \`updateby\` int NULL COMMENT '更新人id', \`updateName\` varchar(255) NULL COMMENT '更新人名称', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`reward_like\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userId\` int NOT NULL, \`rewardId\` int NOT NULL, \`createtime\` datetime(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`updatetime\` datetime(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_a15de7ad01bc6e8d391c92e562\` (\`userId\`, \`rewardId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`exchange\` (\`id\` int NOT NULL AUTO_INCREMENT COMMENT 'id', \`reward\` int NOT NULL COMMENT '花费奖励', \`rewardId\` int NOT NULL COMMENT '奖励id', \`rewardTitle\` varchar(255) NOT NULL COMMENT '奖励标题', \`rewardDescription\` varchar(255) NOT NULL COMMENT '奖励描述', \`status\` enum ('pending', 'in-progress', 'completed', 'reject') NOT NULL COMMENT '状态' DEFAULT 'pending', \`publishId\` int NOT NULL COMMENT '发布人id', \`publishName\` varchar(255) NOT NULL COMMENT '发布人姓名', \`createtime\` datetime(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`updatetime\` datetime(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`createby\` int NOT NULL COMMENT '创建人id', \`createName\` varchar(255) NOT NULL COMMENT '创建人名称', \`updateby\` int NULL COMMENT '更新人id', \`updateName\` varchar(255) NULL COMMENT '更新人名称', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE \`exchange\``);
        await queryRunner.query(`DROP INDEX \`IDX_a15de7ad01bc6e8d391c92e562\` ON \`reward_like\``);
        await queryRunner.query(`DROP TABLE \`reward_like\``);
        await queryRunner.query(`DROP TABLE \`rule\``);
        await queryRunner.query(`DROP TABLE \`message\``);
        await queryRunner.query(`DROP INDEX \`IDX_78a916df40e02a9deb1c4b75ed\` ON \`user\``);
        await queryRunner.query(`DROP INDEX \`IDX_9208163a1d62dbd34ae753fc6f\` ON \`user\``);
        await queryRunner.query(`DROP TABLE \`user\``);
        await queryRunner.query(`DROP TABLE \`sub_task\``);
        await queryRunner.query(`DROP TABLE \`task\``);
        await queryRunner.query(`DROP TABLE \`reward\``);
        await queryRunner.query(`DROP TABLE \`login_log\``);
    }

}
